// <autogenerated />
using MDD4All.DevOpsObserver.ViewModels;
using Microsoft.AspNetCore.Components;

namespace MDD4All.DevOpsObserver.Views
{
    public partial class DevOpsStatusCard
    {
        [Parameter]
        public StatusViewModel DataContext { get; set; }
    }
}