// <autogenerated />
using MDD4All.DevOpsObserver.DataModels;
using MDD4All.DevOpsObserver.ViewModels;
using Microsoft.AspNetCore.Components;

namespace MDD4All.DevOpsObserver.Views
{
    public partial class TrafficLight
    {
        [Parameter]
        public StatusViewModel DataContext { get; set; }

        public bool RedOn 
        { 
            get
            {
                bool result = false;

                if (DataContext.Status.StatusValue == DevOpsStatus.Fail || DataContext.Status.StatusValue == DevOpsStatus.Error)
                {
                    result = true;
                }

                return result;
            }
        }

        public bool AmberOn { get
            {
                bool result = false;

                if (DataContext.Status.StatusValue == DevOpsStatus.Warning)
                {
                    result = true;
                }

                return result;
            }
        }
        
        public bool GreenOn 
        {
            get
            {
                bool result = false;

                if (DataContext.Status.StatusValue == DevOpsStatus.Success || DataContext.Status.StatusValue == DevOpsStatus.Unknown)
                {
                    result = true;
                }

                return result;
            }
        }


    }
}